---
title: "Simple RMarkdown Websites with RStudio & Github"
---

Want to build your own webpage? Need to quickly generate some content and make it publically available? Both? Well, hopefully this is one of the quickest ways to do so using the tools we've already covered (R/RStudio & git/Github). This also assumes you have some knowledge about what an RMarkdown document is, and how to create one.

## Building a Website from RMarkdown Files

There are a few pieces that all need to fit together to create a website using this framework. The main pieces are as follows:

  1. `_site.yml`: This is the road map that provides the outline of your site. It's the bones you stitch everything onto, and the design of how you want things to look overall. 
  2.  `.Rmd`: These are your Rmarkdown files that will be used to render your  webpage content, each `.Rmd` should have a correpsonding `.html`. When we knit, the `.Rmd`, RStudio will create file named the identically, but with a `.html` extension.
  3. `.nojekyll`: This tells github how to build page, and not to use the default web-rendering engine "jekyll".

**Additional Styling Options**

 - `header.html` (*optional*: provides some extra formats/design options for header, footer, etc.)
 - `style.css` (*optional*: provides instructions on how you want website to look)

### Formatting `.yml`

### Formatting Github Repo online


## Resources & Examples

 - http://rmarkdown.rstudio.com/rmarkdown_websites.html
 - http://robertmitchellv.com/blog-building-site-with-rmarkdown.html
 - http://www.alex-singleton.com/
 - https://geographicdatascience.com/2016/08/18/building-an-academic-website-using-rmarkdown/




